### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by Oz5tor** [HLPF/Website-2017#15]
Unified Mail Function
For ease the mailing to users different information (News Letter, Ticket confirmations.)

Start looking at PHPMailer

**Comment by Oz5tor** [comment]
for my own reminder:
![2017-02-26 19_05_43-hlparty - mailtest](https://cloud.githubusercontent.com/assets/1713203/23342213/beb9487c-fc56-11e6-94d6-f0ba324747a6.png)

**Comment by Oz5tor** [comment]
Fixed using a azeHosting mail and SMTP server.

Next to add Function wrapper

**Comment by Oz5tor** [comment]
Function created and added to master. jsut need integration with.
- [ ] Password reset
- [ ] NewsLetter
- [ ] Tickets
- [ ] Membership

**Comment by XDRosenheim** [comment]
This is done, right? 
It works...

**Comment by Oz5tor** [comment]
Inddeed.
