### ISSUE TITLE
Global site settings and variables.

### ISSUE THREAD

**Issue by XDRosenheim** [HLPF/Website-2017#9]
New entry to DB: "Global settings"
Containing: Settings/variable to be used anywhere on the site.

**Comment by XDRosenheim** [comment]
DB table added

**Comment by XDRosenheim** [comment]
Started the file for global settings (3868fca6819e8b60166dd2307419b50d821e6c72)

**Comment by Oz5tor** [comment]
Values  for the OneAll login api On or Off

**Comment by XDRosenheim** [comment]
All variables can be found under `$_GLOBAL['your_variable_from_database']`
